FROM python:3.9.1

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/app

COPY api/poetry.lock api/pyproject.toml ./

RUN pip install --upgrade pip
RUN pip install poetry

RUN poetry config virtualenvs.create false && poetry install
# RUN poetry config virtualenvs.create false

EXPOSE 8000
